services:
  backend:
    build: ./bookworm-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=bookworm
      - DB_USERNAME=root
      - DB_PASSWORD=example
    volumes:
      - ./bookworm-api:/var/www/html
      - ./bookworm-api/vendor:/var/www/html/vendor
    networks:
      - app-network

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookworm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge