<?php

namespace Tests\Domains\Books\Services;

use App\Domains\Books\DTOs\Services\BooksApiGetOptionsDTO;
use App\Domains\Books\Exceptions\BooksApiException;
use App\Domains\Books\Services\APIs\ExternalBookService;
use App\Domains\Books\Services\BooksApiService;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;

class BooksApiServiceTest extends TestCase
{
    private BooksApiService $service;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = app()->make(BooksApiService::class);
    }

    /**
     * @throws BindingResolutionException
     * @throws BooksApiException
     */
    public function testGetBooks(): void
    {
        $options = new BooksApiGetOptionsDTO();
        $books = $this->service->getBookDTOs($options);

        assert($books instanceof Collection, 'Collection expected');

        $this->assertNotEmpty($books, 'Collection should not be empty');

        $this->assertNotEmpty($books[0]->title, 'Title should not be empty');

        Log::info('Books: ' . count($books));
    }
}
